-- Feedback Analysis Portal — MySQL schema (table names match assignment spelling)
CREATE DATABASE IF NOT EXISTS feedback_portal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE feedback_portal;

CREATE TABLE IF NOT EXISTS REGISTRTION (
  NAME   VARCHAR(120) NOT NULL,
  MOBILE VARCHAR(20)  NOT NULL,
  EMAIL  VARCHAR(190) NOT NULL PRIMARY KEY,
  PWD    VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ADMIN (
  EMAIL VARCHAR(190) NOT NULL PRIMARY KEY,
  PWD   VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FEEDBACK (
  ID        INT AUTO_INCREMENT PRIMARY KEY,
  NAME      VARCHAR(120) NOT NULL,
  EMAILID   VARCHAR(190) NOT NULL,
  FEEDBACK  TEXT         NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Default admin (change password in production)
INSERT INTO ADMIN (EMAIL, PWD) VALUES ('admin@portal.local', 'admin123')
  ON DUPLICATE KEY UPDATE EMAIL = EMAIL;
